import type { AchievementDef } from "@/lib/types";

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: "first-lesson",
    title: "First Steps",
    description: "Complete your very first lesson.",
    emoji: "🌱",
    check: (c) => c.completedCount >= 1,
  },
  {
    id: "five-lessons",
    title: "Getting Warmed Up",
    description: "Complete 5 lessons.",
    emoji: "🔥",
    check: (c) => c.completedCount >= 5,
  },
  {
    id: "ten-lessons",
    title: "Math Explorer",
    description: "Complete 10 lessons.",
    emoji: "🧭",
    check: (c) => c.completedCount >= 10,
  },
  {
    id: "twenty-lessons",
    title: "Math Champion",
    description: "Complete 20 lessons.",
    emoji: "🏆",
    check: (c) => c.completedCount >= 20,
  },
  {
    id: "first-perfect",
    title: "Perfect!",
    description: "Earn 3 stars on a lesson.",
    emoji: "⭐",
    check: (c) => c.perfectLessons >= 1,
  },
  {
    id: "five-perfect",
    title: "Star Collector",
    description: "Earn 3 stars on 5 different lessons.",
    emoji: "✨",
    check: (c) => c.perfectLessons >= 5,
  },
  {
    id: "stars-25",
    title: "Shining Bright",
    description: "Collect 25 stars in total.",
    emoji: "🌟",
    check: (c) => c.totalStars >= 25,
  },
  {
    id: "stars-50",
    title: "Superstar",
    description: "Collect 50 stars in total.",
    emoji: "💫",
    check: (c) => c.totalStars >= 50,
  },
  {
    id: "domain-mult",
    title: "Times Tables Master",
    description: "Finish all Multiplication & Division lessons.",
    emoji: "✖️",
    check: (c) => (c.domainCompletion["mult-div"] ?? 0) >= 9,
  },
  {
    id: "domain-place",
    title: "Number Ninja",
    description: "Finish all Place Value lessons.",
    emoji: "🔢",
    check: (c) => (c.domainCompletion["place-value"] ?? 0) >= 5,
  },
  {
    id: "domain-frac",
    title: "Fraction Wizard",
    description: "Finish all Fractions lessons.",
    emoji: "🍕",
    check: (c) => (c.domainCompletion["fractions"] ?? 0) >= 5,
  },
  {
    id: "domain-meas",
    title: "Measure Master",
    description: "Finish all Measurement & Data lessons.",
    emoji: "📏",
    check: (c) => (c.domainCompletion["measurement"] ?? 0) >= 8,
  },
  {
    id: "domain-geo",
    title: "Shape Sorter",
    description: "Finish all Geometry lessons.",
    emoji: "🔷",
    check: (c) => (c.domainCompletion["geometry"] ?? 0) >= 3,
  },
  // Preschool domain achievements
  {
    id: "ps-counting",
    title: "Counting Champ",
    description: "Finish all Preschool Counting lessons.",
    emoji: "🔢",
    check: (c) => (c.domainCompletion["ps-counting"] ?? 0) >= 4,
  },
  {
    id: "ps-shapes",
    title: "Shape Spotter",
    description: "Finish all Preschool Shapes & Colors lessons.",
    emoji: "🎨",
    check: (c) => (c.domainCompletion["ps-shapes-colors"] ?? 0) >= 3,
  },
  {
    id: "ps-patterns",
    title: "Pattern Pro",
    description: "Finish all Preschool Patterns lessons.",
    emoji: "🔴",
    check: (c) => (c.domainCompletion["ps-patterns"] ?? 0) >= 2,
  },
  {
    id: "ps-comparing",
    title: "Comparison Star",
    description: "Finish all Preschool Comparing lessons.",
    emoji: "⚖️",
    check: (c) => (c.domainCompletion["ps-comparing"] ?? 0) >= 3,
  },
  {
    id: "ps-first-math",
    title: "First Math Hero",
    description: "Finish all Preschool First Math lessons.",
    emoji: "✨",
    check: (c) => (c.domainCompletion["ps-first-math"] ?? 0) >= 3,
  },
  {
    id: "streak-3",
    title: "On a Roll",
    description: "Keep a 3-day streak going.",
    emoji: "📈",
    check: (c) => c.streak >= 3,
  },
];
