import Image from "next/image";
import Link from "next/link";
import { BookOpen, Building2, Globe2, Heart, Server, ShieldCheck } from "lucide-react";
import { getSiteSettings } from "@/lib/settings";

export const dynamic = "force-dynamic";

export default async function SupportPage() {
  const settings = await getSiteSettings().catch(() => null);
  const cashApp = settings?.cashappHandle?.trim() ?? "";
  const zelle = settings?.zelleInfo?.trim() ?? "";
  return (
    <main id="main-content" className="min-h-screen bg-[#fff9ec] text-[#2f281d]">
      <header className="border-b border-amber-100 bg-white/90"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link href="/"><Image src="/brand/math-stars-logo.png" alt="Math Stars" width={1400} height={360} className="h-12 w-auto" /></Link><nav className="flex items-center gap-4 text-sm font-bold"><Link href="/transparency">Transparency</Link><Link href="/signin" className="rounded-full bg-emerald-800 px-5 py-3 text-white">Family sign in</Link></nav></div></header>
      <section className="bg-[radial-gradient(circle_at_top_right,#ffe8a8,transparent_42%),linear-gradient(135deg,#183f2e,#2d6b4b)] px-5 py-16 text-white"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_340px] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-200">For parents, partners, and supporters</p><h1 className="mt-3 max-w-3xl font-display text-5xl font-black leading-tight">Help keep excellent math learning free, offline, and open to every child.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-emerald-50/85">Children never see donation requests inside their learning experience. Support is completely voluntary and no lesson, game, reward, or report is ever locked behind payment.</p></div><div className="rounded-[30px] border border-white/20 bg-white/10 p-6 text-center backdrop-blur"><Heart className="mx-auto h-14 w-14 fill-rose-400 text-rose-400" /><p className="mt-4 font-display text-2xl font-black">Math Stars belongs everywhere.</p><p className="mt-2 text-sm leading-6 text-emerald-50/80">Your gift helps a child learn on a shared phone, a school computer, or a local Wi-Fi classroom with no internet.</p></div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-12"><h2 className="font-display text-3xl font-black">What support funds</h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Fund icon={<Server />} title="Reliable access" text="Hosting, security, backups, and safe synchronization." /><Fund icon={<BookOpen />} title="Free curriculum" text="Preschool through 4th Grade lessons and new learning worlds." /><Fund icon={<Globe2 />} title="Offline reach" text="Grade packs, low-data tools, translations, and school kits." /><Fund icon={<Building2 />} title="Community pilots" text="Device preparation, teacher support, and local training." /></div>
        <div className="mt-10 grid gap-5 lg:grid-cols-2"><section className="rounded-[28px] border-2 border-emerald-200 bg-white p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">One-time or recurring support</p><h2 className="mt-2 font-display text-3xl font-black">Donate directly</h2>{cashApp || zelle ? <div className="mt-6 space-y-3">{cashApp && <DonationMethod label="Cash App" value={cashApp} href={`https://cash.app/${cashApp.replace(/^\$/, "$")}`} />}{zelle && <DonationMethod label="Zelle" value={zelle} />}</div> : <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-900">Donation details are being prepared. Please check back soon or contact the Math Stars team through the public project page.</p>}<p className="mt-5 text-xs leading-5 text-stone-500">Donations are voluntary. Math Stars does not sell child data or display advertising to children.</p></section><section className="rounded-[28px] bg-[#ede7ff] p-7"><ShieldCheck className="h-9 w-9 text-violet-700" /><h2 className="mt-4 font-display text-3xl font-black">Sponsor a school or community</h2><p className="mt-3 leading-7 text-stone-700">Partners can fund an offline school kit, shared devices, local teacher training, translation, or a pilot in Liberia and another African community.</p><a href="mailto:hello@mathstars.net?subject=Math%20Stars%20community%20partnership" className="mt-6 inline-flex rounded-full bg-violet-800 px-6 py-3 font-black text-white">Discuss a partnership</a></section></div>
        <div className="mt-10 text-center"><Link href="/transparency" className="font-black text-emerald-800 underline underline-offset-4">See how Math Stars measures access and protects families</Link></div>
      </section>
    </main>
  );
}

function Fund({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-3xl border border-stone-200 bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-100 text-emerald-800 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h3 className="mt-4 font-display text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{text}</p></article>; }
function DonationMethod({ label, value, href }: { label: string; value: string; href?: string }) { const content = <div className="flex items-center justify-between gap-3 rounded-2xl bg-emerald-50 p-4"><span><strong className="block">{label}</strong><span className="text-sm text-stone-600">{value}</span></span>{href && <span className="font-black text-emerald-800">Open →</span>}</div>; return href ? <a href={href} target="_blank" rel="noreferrer">{content}</a> : content; }
