import Image from "next/image";
import Link from "next/link";
import { db } from "@/lib/db";
import { listGradePackMetadata } from "@/lib/offline/grade-packs";

export const dynamic = "force-dynamic";

export default async function TransparencyPage() {
  const [families, learners, completedLessons] = await Promise.all([
    db.familyAccount.count().catch(() => 0),
    db.student.count().catch(() => 0),
    db.lessonProgress.count({ where: { status: "completed" } }).catch(() => 0),
  ]);
  const packs = listGradePackMetadata();
  return <main id="main-content" className="min-h-screen bg-[#f7f5ef] text-[#18243b]"><header className="border-b border-stone-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-5"><Link href="/"><Image src="/brand/math-stars-logo.png" alt="Math Stars" width={1400} height={360} className="h-12 w-auto" /></Link><Link href="/support" className="rounded-full bg-rose-600 px-5 py-3 text-sm font-black text-white">Support the mission</Link></div></header><section className="mx-auto max-w-6xl px-5 py-14"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-700">Public accountability</p><h1 className="mt-3 max-w-4xl font-display text-5xl font-black">Free means every child gets the whole learning experience.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-stone-600">Math Stars is being built as an access-first education project. These commitments guide product decisions, partnerships, and how voluntary support is used.</p><div className="mt-10 grid gap-4 sm:grid-cols-3"><Metric value={families} label="family accounts" /><Metric value={learners} label="learner profiles" /><Metric value={completedLessons} label="lessons completed" /></div><div className="mt-10 grid gap-5 lg:grid-cols-2"><Commitment title="Always free for children" text="No subscriptions, no premium lessons, no pay-to-win rewards, and no advertising inside the learner experience." /><Commitment title="Private by design" text="Children do not need email addresses. Math Stars does not store precise location, advertising IDs, or open child profiles." /><Commitment title="Offline first" text={`${packs.length} versioned grade packs cover ${packs.reduce((sum, pack) => sum + pack.lessonCount, 0)} lessons from Preschool through 4th Grade, with resumable downloads and safe delayed sync.`} /><Commitment title="Transparent support" text="Donations fund access, curriculum, infrastructure, translation, school kits, and community pilots. Donation requests appear only in adult-facing spaces." /></div><section className="mt-10 rounded-[30px] bg-[#172647] p-7 text-white"><h2 className="font-display text-3xl font-black">What we will report as the project grows</h2><ul className="mt-5 grid gap-3 text-sm leading-6 text-blue-50/85 md:grid-cols-2"><li>• Active learners and completed learning sessions</li><li>• Offline pack downloads and successful synchronizations</li><li>• Pilot schools, communities, and supported devices</li><li>• Curriculum, language, and accessibility coverage</li><li>• Service reliability and major incidents</li><li>• Donation use by program category</li></ul></section><div className="mt-10 flex flex-wrap gap-3"><Link href="/privacy" className="rounded-full border-2 border-stone-300 bg-white px-6 py-3 font-black">Read the privacy policy</Link><Link href="/support" className="rounded-full bg-emerald-800 px-6 py-3 font-black text-white">Support Math Stars Anywhere</Link></div></section></main>;
}

function Metric({ value, label }: { value: number; label: string }) { return <div className="rounded-3xl border border-stone-200 bg-white p-6"><p className="text-4xl font-black tabular-nums">{value.toLocaleString()}</p><p className="mt-1 text-sm font-bold text-stone-600">{label}</p></div>; }
function Commitment({ title, text }: { title: string; text: string }) { return <article className="rounded-3xl border border-stone-200 bg-white p-6"><h2 className="font-display text-2xl font-black">{title}</h2><p className="mt-3 leading-7 text-stone-600">{text}</p></article>; }
